### ISSUE TITLE
Document command line invocation

### ISSUE THREAD

**Issue by lmb** [wellington/wellington#109]
This might sound really stupid, but I haven't been able to get wt to build files where I want. This is on `0.9.1`, OS X.

File structure:
```
project
 - scss
   - libraries
   - style.scss
 - static
```

`libraries` contains a bunch of subfolders with includes. With a shell in `project` I can't make wt output to `static`.

I've tried this: `wt -b=static/ -p=scss/libraries/ scss/style.scss` (and lots of other combinations), but no luck. Can you add examples to the README that explain how to do this?

Much appreciated!

**Comment by drewwells** [comment]
Absolutely! There needs to be more examples of how to use wt. One main difference with wt is that the files are listed manually rather than recursively being found in the project folder. That will change with #102. Afterwards, it will find files recursively.

Are you getting no files in static/ or just one output (from scss/style.scss). Is there any output from wt after running that command?

**Comment by lmb** [comment]
The result is a style.css written in  `project`. Weirdly, I've tried cd'
ing to `scss` and even then style.css is written to project.

**Comment by drewwells** [comment]
Hmm that is odd. Can you give HEAD a try? Since you're on OS X, it's easy to install.

`brew install --HEAD wellington`

**Comment by lmb** [comment]
That gives me

```
==> Cloning https://github.com/wellington/wellington.git
Updating /Library/Caches/Homebrew/wellington--git
==> Checking out branch master
==> Cloning https://github.com/tools/godep.git
Updating /Library/Caches/Homebrew/wellington--github.com-tools-godep--git
==> Checking out revision fe7138c011ae7875d4af21efe8b237f4987d8c4a
==> Cloning https://github.com/kr/fs.git
Updating /Library/Caches/Homebrew/wellington--github.com-kr-fs--git
==> Checking out revision 2788f0dbd16903de03cb8186e5c7d97b69ad387b
==> Cloning https://github.com/golang/tools.git
Updating /Library/Caches/Homebrew/wellington--golang.org-x-tools--git
==> Checking out revision ea5101579e09ace53571c8a5bae6ebb896f8d5e4
==> go install
==> bin/godep restore
==> make deps
==> go build -ldflags -X main.version v0.9.1 -o dist/wt wt/main.go
dist/wt
wt/main.go

# command-line-arguments
wt/main.go:196: undefined: ConfigParse
couldn't understand kern.osversion `14.4.0'
```

Probably worth another ticket.

**Comment by drewwells** [comment]
You need to upgrade the xcode cli tools. xcode-select --install

**Comment by drewwells** [comment]
I've added a basic example using the cli. Let me know what you think: http://getwt.io/docs/usage/

Thanks again for trying out the product!

**Comment by drewwells** [comment]
Closing this
