### ISSUE TITLE
Misspelled "@incldue" isn't throwing an error

### ISSUE THREAD

**Issue by pierceray** [wellington/wellington#111]
We came across a misspelled "@incldue" in our source code.  Wellington doesn't throw an error for unknown directive.

```
.foo {
    color: red;
    @incldue box-sizing(border-box);
}
```

**Comment by andystalick** [comment]
This is actually a libsass issue, I've reported it here:
https://github.com/sass/libsass/issues/1406

**Comment by drewwells** [comment]
Unfortunately, Ruby Sass/libsass treat this as perfectly valid Sass (by ignoring it). http://sassmeister.com/gist/fed361fd071959f14732

It would need to be an part of the Ruby spec for libsass to consider this a bug.

**Comment by drewwells** [comment]
There's no mention of what Sass will do when a directive is unknown. My assumption is that unknown directives `@{word}` are assumed to be valid CSS directives. So to support these, Sass compiler simply dumps them to CSS unchanged. reference: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#directives

**Comment by pierceray** [comment]
That seems like a known set of directives and parseable set of mixin directives.
