### ISSUE TITLE
Return from sprite-map() is a string instead of a map or list

### ISSUE THREAD

**Issue by andystalick** [wellington/wellington#118]
In attempting to debug why sprite-position() doesn't work, I ran into this:

```
$foo: sprite-map("new/hidpi/*.png", $spacing: 12px);
@debug type-of($foo);
@debug $foo;
```
upon running the code
```
www/gui/sass/main.scss:4: DEBUG: string
www/gui/sass/main.scss:4: DEBUG: new/hidpi/*.png12
```

**Comment by drewwells** [comment]
that's correct, it is stored as a string internally which is used by other sprite-{fn} to lookup which map is being referenced.

I guess it would be nice to expose a way to find the images being matched by sprite-map(). Have you tried the same in Compass?

**Comment by andystalick** [comment]
Compass sees it way differently.
$foo is type-of compass::sassextensions::sprites::spritemap
and 
the value is something like url('../../im/sass/csat-icons/hidpi-s16798cf44c.png')
I'm trying to get this line of code to work in wt:
```
background-position: $offset-x ceil(nth(sprite-position($sprite, $name), 2) / 2);
```

**Comment by drewwells** [comment]
sprite-position doesn't return a list, remove the `nth(` and `, 2)` and see if that works

**Comment by andystalick** [comment]
sprite-position doesn't return anything, it just passes straight through to css with the variables interpreted.
```
sprite-position(sass/new/hidpi/*.png12, iconHome)
```
If you run
```
background-position: $offset-x ceil( sprite-position($sprite, $name) / 2);
```
it throws the error
```
argument `$number` of `ceil($number)` must be a number
```

**Comment by drewwells** [comment]
Ahh now I see, it's trying to parse `{x}px {y}px` as a list, nth selects y and you get output. What output are you getting from `sprite-position`?

**Comment by andystalick** [comment]
sprite-position doesn't get parsed out of the scss, it just falls through to css.
Given the example scss
```
$foo: sprite-map("new/hidpi/*.png", 100px);
span {
	background-position: sprite-position($foo, debug);
}
```
you get the rendered css
```
span {
  background-position: sprite-position(new/hidpi/*.png100, debug); 
}
```

**Comment by drewwells** [comment]
@andystalick I've added an example showing how this works: http://godoc.org/github.com/wellington/wellington/handlers#example-Sprite--Position expand the accordion called "Example (Position)"

Input
```
$map: sprite-map("*.png", 10px);
div.retina {
  background-position: 10px ceil(nth(sprite-position($map, "140"), 2) /2 );
}
```

Output
```
div.retina {
  background-position: 10px -74px; }
```

**Comment by drewwells** [comment]
Does this look good on 0.9.3?

**Comment by drewwells** [comment]
closing
