### ISSUE TITLE
Multiple-selector mixins don't apply correctly with placeholder extends

### ISSUE THREAD

**Issue by andystalick** [wellington/wellington#124]
This one is a little complicated, but I confirmed the behavior against sassc 3.2.5. I suspect it may have something to do with libsass: 3.2.5-155-g295b specifically.

The Sass code in this gist should render CSS that applies to each of the input types, as shown in the sample output.

https://gist.github.com/andystalick/aeca39897266c19f0455

**Comment by drewwells** [comment]
What is the output you are seeing from wt? It's probably a bug in the packaged libsass. 3.3 rc is landing very soon. They have a few release blockers, but I can ship a release once those are fixed.

**Comment by andystalick** [comment]
Output in wt 0.9.2 looks like this:
```
/* line 13, stdin */
input[type="text"], textarea {
  font-family: Arial;
  border: 1px solid #CCC;
  border-radius: 3px;
  font-size: 1em;
  padding: 0.5em;
  width: 100%;
  max-width: 600px;
  display: block; }
```

**Comment by drewwells** [comment]
Hmm, I think this might be an issue on libsass master too. I still see this on my development branch

**Comment by andystalick** [comment]
I guess the question, then, is which version of libsass to bundle, release or master. My feeling is it ought to be release, that master is prone to unpredictable bugs.

**Comment by drewwells** [comment]
I tagged 0.9.2 as pre-release for that reason. 0.9.1 is built against the libsass 3.2.5 release. I can push a another pre-release when this gets fixed upstream.

**Comment by andystalick** [comment]
Ah cool, makes sense. Thanks!

**Comment by drewwells** [comment]
This is fixed in libsass master now
