### ISSUE TITLE
Watching directories

### ISSUE THREAD

**Issue by ysimonson** [wellington/wellington#132]
Is it possible to watch a directory? I see there's [a merged PR](https://github.com/wellington/wellington/issues/128) to address at least part of this, but I can't figure out the syntax to get it to work.

`wt watch [indir] [outdir]` seems to spit results to stdout. `wt watch --build=[outdir] [indir]` does something, but I'm not sure what.

**Comment by drewwells** [comment]
hey @ysimonson thanks for checking out the project!

Passing paths is only available in 1.0.0 beta1. Available here: https://github.com/wellington/wellington/releases/tag/v1.0.0-beta1

If you're using OS X, you can also install it with brew by passing the devel flag `brew install --devel wellington

I appreciate any feedback on the beta, there's a lot of new plumbing that might have created some regressions

**Comment by drewwells** [comment]
Oh wait, you are right the watcher isn't recursively locating directories. I need to add this.

**Comment by ysimonson** [comment]
Thanks @drewwells! I was actually trying this against HEAD because it wasn't in homebrew's stable version. With either of the above commands, `outdir` remains empty, even if you update one of the files at the root of `indir`.

**Comment by drewwells** [comment]
Good catch, the watcher was not starting in beta1. You should be good to go now and it will watch the entire folder.

This is the support format `wt watch --build=[outdir] [indir] [indir2] [indir3]`. I never understood the logic behind the Sass `compile indir outdir` convention :)
