### ISSUE TITLE
Watcher doesn't watch

### ISSUE THREAD

**Issue by moorereason** [wellington/wellington#144]
I'm new to Wellington and SASS.  Attempting to run Wellington in watch mode as I build out a Hugo site, but Wellington's watcher doesn't work.  I've tried the following but neither work:

```
wt watch --debug -b themes/example/static/css themes/example/sass/app.scss
wt watch --debug -b themes/example/static/css themes/example/sass
```
I only have one sass file (`app.scss`).  Running just in compile mode works properly.

I'm running Wellington HEAD (9d5573d8) with Go 1.5.1 linux/amd64.  Wellington tests (`go test ./...`) run successfully.  I'm editing my scss file in Vim.  Hugo (also HEAD) does detect the scss file change and reloads the site, but for no reason really since the css file has not been updated by Wellington.

Smells like a bug.  :bug:

**Comment by drewwells** [comment]
Thanks for the report!

It appears to be broken when a build directory is passed which is what I get for having a stdout only test. For the record, you should see a `Rebuilt: {filename}` every time a file changes. Otherwise, something has gone wrong!

**Comment by moorereason** [comment]
Just wanted to confirm that it's working for me now.  Thanks!

**Comment by drewwells** [comment]
Awesome, thanks for verifying.
