### ISSUE TITLE
Cache busters

### ISSUE THREAD

**Issue by ysimonson** [wellington/wellington#145]
Is it possible to create cache-busting references to assets in wellington? Like compass' [URL helpers](http://compass-style.org/reference/compass/helpers/urls/)? If not, would you accept a PR that adds it?

**Comment by drewwells** [comment]
No Wellington doesn't do this, but sure I'd accept a PR to add it.

It's a bit tricky to add this, since there's no central notion of path building. Here's some locations that build paths that requires updating:

sprites: https://github.com/wellington/spritewell/blob/master/sprite.go#L273
image-url(): https://github.com/wellington/wellington/blob/master/handlers/handlers.go#L38
fonts: https://github.com/wellington/wellington/blob/master/handlers/misc.go#L48

Then, go-libsass.Context would need a new option for it: https://github.com/wellington/go-libsass/blob/master/context.go#L18 at least until I get rid of this terrible struct!

And the compiler needs a new `option` to set cache bust: https://github.com/wellington/go-libsass/blob/master/compiler.go#L30-L36

**Comment by ysimonson** [comment]
I was thinking of add a `cache-busted-url()` libsass handler. It would take a path, e.g. `cache-busted-url('foo/bar.png')`, and generate `url('foo/bar.png?v=hashsum_of_file')`. For this setup, options wouldn't be needed AFAICS. Would this suffice?

**Comment by drewwells** [comment]
There's a compass option for adding cache busting to image-url: http://compass-style.org/reference/compass/helpers/urls/#image-url

We should probably support that for better compatibility with existing Sass code.

**Comment by ysimonson** [comment]
For our needs that implementation wouldn't work so well. Locally, our assets are hosted through a server that doesn't make use of cache busters. But deployed servers do make use of them. So it would be very easy for one of our designers to update an asset without remembering to update the referencing stylesheets.

I get the drive to be compatible with compass though. In that case, we could consider just maintaining a private copy of wellington with this extension.

Shall I close the ticket?

**Comment by drewwells** [comment]
Ahh, I see what you are saying. I agree, it makes more sense that this works as an environment variable for the compiler. We did the same thing with Compass with a config file.

I'm not following the need for a special Sass function. What if it's a cli argument `wt --no-cache` then any path that is generated gets appended a random string. In development, you wouldn't specify this cli argument and caching would be enabled.

**Comment by drewwells** [comment]
There's no need to fork, I'm interested in supporting this feature. With the way that I have implemented sprites, you wouldn't need to cache bust them. So really, you only need to modify the output of image-url() https://github.com/wellington/wellington/blob/master/handlers/handlers.go#L38 with a random string when the cli argument is present.

**Comment by ysimonson** [comment]
A random string would change the `v` query parameter on every sass change or re-compile. At deploy-time, the sass would be re-compiled, and all the `v` query parameters would be updated. While this would ensure outdated assets would never be served, it would also invalidate the cache overly-aggressively, and defeat the purpose of the cache busters. The cache busters should be based on the contents of the file, because then the query parameters only get updated when the actual contents change.

image-url() works though, so long as we can reference fonts, etc. using it as well. I suppose we could just set the image path to be the same as the sass path, and then reference images and fonts relative to the sass file. That should work, right?

**Comment by drewwells** [comment]
Yes, adding a random string would cause the cache to be invalidated every time.

It's possible to evaluate file contents and compute a hash, however it would add overhead to compiling. While those hashes are being calculated, libsass would be hung waiting for the file string. I'll need to think on the best approach for intelligent caching. It would be more efficient to place tokens in the output so libsass can complete, then replace them in a post-compile step before writing out to disk.

There's a font-url(), but you can just use image-url and make the files relative to your Sass.

**Comment by drewwells** [comment]
@ysimonson I've added some basic timestamp cache busting on master. Try it out and see if it does what you need.

```
-> % echo '@font-face { src: font-url("arial.eot"); }' | wt --font ../test/font --cachebust compile
Reading from stdin, -h for help
@font-face {
  src: url("../test/font/arial.eot?c5e8cf8f"); }
2015/11/20 02:56:49 Compilation took: 1.390455ms

-> % echo '@font-face { src: font-url("arial.eot"); }' | wt --font ../test/font compile
Reading from stdin, -h for help
@font-face {
  src: url("../test/font/arial.eot"); }
2015/11/20 02:56:56 Compilation took: 1.06852ms
```

**Comment by ysimonson** [comment]
Awesome! Will take a look shortly.

**Comment by ysimonson** [comment]
That strategy would rely on file mtimes, correct? If so, that would work if you assume deployments always happen from the same system + that system doesn't wipe the repo on deployment (as CI systems will do in some contexts.) I think in most cases, one of these will be invalidated.

For us, we generally do deployments from CircleCI, but AFAIK they don't guaranteed to preserve file mtimes. It should be cleared when you build with a clear cache. We also do deployments occasionally directly from dev machines, which would certainly change the file mtime. Between the two of these, I think the mtimes would change frequently even when the contents are preserved.

**Comment by drewwells** [comment]
CircleCI doesn't preserve timestamps, it would be a bad idea to do too much caching in your build b/c failures could occur just from caching.

It is possible to do this sort of caching, but it is expensive to calculate hash sums at the time that they would be useful. I'm starting to see why you liked the idea of adding this as a separate function.

In lieu of adding a new handler, which can be created here: https://github.com/wellington/wellington/tree/master/handlers maybe it makes sense to offer up multiple cache busting methods. The current one (timestamp) and a more targeted one (md5).

Instead of -cachebust being a bool, it accepts a string. `--cachebust=[ts,md5]`

**Comment by drewwells** [comment]
This is done, see comment here: https://github.com/wellington/wellington/issues/158#issuecomment-159995811

**Comment by drewwells** [comment]
Re-open if there's issues! I need to ship 1.0.2 for some misc fixes

**Comment by ysimonson** [comment]
Awesome! Thank you again @drewwells - will take a look.

**Comment by drewwells** [comment]
No problem @ysimonson, thanks for filing the issue.

I'm not sure what your stack looks like, but there's a [grunt](https://github.com/wellington/grunt-wellington) that's used in production and I'm cobbling together scraps to make a [gulp plugin](https://github.com/wellington/gulp-wt).

Note though, they both vendor `wt` in the node_modules directory, which makes using latest wellington a little trickier.
