### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by ysimonson** [wellington/wellington#147]
I tried running `make test`, and got an issue with a method being undocumented:

    $ make test
    go get golang.org/x/tools/cmd/vet
    # retrieve lint and test deps
    go get github.com/axw/gocov/gocov
    go get github.com/mattn/goveralls
    go get golang.org/x/tools/cmd/goimports
    go get github.com/golang/lint/golint
    go get golang.org/x/tools/cmd/cover
    scripts/goclean.sh
    filewatcher.go:88:1: exported method SafePartialMap.Add should have comment or be unexported

It seems like circleci is running the same make target - not sure how it's passing.

**Comment by drewwells** [comment]
Pull latest master, that was fixed last night.

**Comment by ysimonson** [comment]
*facepalm* right
