### ISSUE TITLE
GO15VENDOREXPERIMENT=1 build errors

### ISSUE THREAD

**Issue by rohanthewiz** [wellington/wellington#164]
Out of the box, building with GO15VENDOREXPERIMENT=1, fails with go-libsass submodule errors (even though I tried to do a `git submodule update` in the go-libsass project ). I had to build with:

    GO15VENDOREXPERIMENT=0 go get -u github.com/wellington/wellington
    cd $GOPATH/src/github.com/wellington/wellington/wt // this should be automatic (idk how)
    GO15VENDOREXPERIMENT=0 go build // produces the 'wt' executable
    cp wt $GOPATH/bin // go install doesn't seem to work here, so manual copy

**Comment by drewwells** [comment]
If you specify the cli command, `go get -u github.com/wellington/wellington/wt` it will put a binary in $GOPATH/bin. After checkout, you can still do `go install github.com/wellington/wellington/wt` to get a binary. 

I'm taking a look at the submodule problem. Submodules really suck even with the go toolchain. I regret switching to them.

**Comment by drewwells** [comment]
@rohanthewiz can you give this another go? I've removed the nested submodules that's causing these build errors.

`go get -u github.com/wellington/wellington/wt`

**Comment by rohanthewiz** [comment]
It works! Thanks! I tried on a clean machine and it automatically installed.

**Comment by drewwells** [comment]
that path looks off `src/github.com/vendor/github.com`

**Comment by drewwells** [comment]
@rohanthewiz can you try this again on master? Until the submodules bugs are fixed in 1.6, I'll just be manually managing deps.

**Comment by drewwells** [comment]
Closing, please reopen if you still have problems
