### ISSUE TITLE
Add support for generating sourcemaps

### ISSUE THREAD

**Issue by jakesym** [wellington/wellington#178]
It would be awesome to have wellington generate .map files for development.

**Comment by drewwells** [comment]
This should be trivial to add since go-libsass already supports toggling sourcemaps https://godoc.org/github.com/wellington/go-libsass#SourceMap

It looks like all that is needed is to expose the behavior as a cli argument.

**Comment by drewwells** [comment]
Compass calls this `sourcemap` in config file. It's two words, so the option will be `--source-map`. The output should be generated alongside the css file.

```
file.scss
build/file.css
build/file.css.map
```

**Comment by drewwells** [comment]
This is on master

`go get -u github.com/wellington/wellington/wt` to build from source. 

`wt --source-map -b some/build/dir some/sass/file.sass` to use it
