### ISSUE TITLE
wellington watch does not work when files edited by osx apps

### ISSUE THREAD

**Issue by steveetm** [wellington/wellington#182]
I successfully set up a wellington and use file watcher with
`wt watch file.scss`

Everything is fine when I edit the file in terminal(echo, mcedit, nano), it triggers a rebuild.
But if I edit the file from webstorm or osx's texteditor then nothing happens. For example editing that specific file textEdit, webstorm immediately ask for reload because the file changed, but wt ignores that.

Another strange issue if I edit the file with vi then the following printed by wt:
rebuild error: partial map lookup failed: file.scss.swp 
So I think something is wrong with the file watcher atm.

Using OSX El Captain.
Other tools like grunt-watch, node-sass's watch, compass watch, sass watch, etc is just working fine.

**Comment by drewwells** [comment]
I'll take a look at this soon. This is the second OS X bug with the watcher. Go support for native OS X file events is a little bit behind other OS's. I need to take a deeper look at the library we are using.

Which version of wellington are you using, built from master? `wt -v` to check

**Comment by drewwells** [comment]
reference: https://github.com/fsnotify/fsevents @outclassed

**Comment by steveetm** [comment]
wt -v
   libsass: 3.3.2
Wellington: v1.0.2

**Comment by fgimian** [comment]
Same problem here with different versions:

```
   libsass: 3.2.5-289-g6075
Wellington: v0.9.3
```

**Comment by drewwells** [comment]
@fgimian is this also on OS X? have you tried Linux?

**Comment by fgimian** [comment]
Hey @drewwells, yup, this is installed via Homebrew on OS X.  Unfortunately I haven't tried it on Linux just yet though :smile:

**Comment by drewwells** [comment]
Interesting behavior, EMACS edits cause rebuilds but textedit does not.

**Comment by drewwells** [comment]
Confirmed fsevents cgo wrapper gets updates even when textedit modifies a file.

```
2016/04/06 15:59:10 append /Users/drew/src/github.com/wellington/wellington/test
File watcher started use `ctrl+d` to exit
2016/04/06 15:59:10 starting up...
2016/04/06 15:59:10 watching [/Users/drew/src/github.com/wellington/wellington/test]
2016/04/06 15:59:18 msg [{/Users/drew/src/github.com/wellington/wellington/test/mixin.scss 108544 22195472} {/Users/drew/src/github.com/wellington/wellington/test/mixin.scss.sb-966f62c4-xCeRZM 88576 22195478}]
2016/04/06 15:59:18 fsevents.Event{Path:"/Users/drew/src/github.com/wellington/wellington/test/mixin.scss", Flags: 0x1a800, ID: 0x152ad10}
2016/04/06 15:59:18 fsevents.Event{Path:"/Users/drew/src/github.com/wellington/wellington/test/mixin.scss.sb-966f62c4-xCeRZM", Flags: 0x15a00, ID: 0x152ad16}
```

The fsevents API is rough, so the code to use it is not ideal. Although, we should be able to remove this filewatcher-fsevents shim once fsevents gets merged with https://godoc.org/gopkg.in/fsnotify.v1.
