### ISSUE TITLE
Brew version of wellington doesn't compile for Mac OS Sierra

### ISSUE THREAD

**Issue by pierceray** [wellington/wellington#188]
The brew version of wellington looks to be trying to compile version 0.9.3.  Mac OS Sierra can't compile that.

**Comment by drewwells** [comment]
Yeah that version won't compile with go171. I don't have my computer so
can't fix it until Sunday or Monday. All that is needed is to update the
version and sha
https://github.com/Homebrew/legacy-homebrew/commit/8da14674ce6626e8083daf347acd38556c83b752

It isn't too hard to do just no computer
