### ISSUE TITLE
Comment generation is full path to files causes commits by team members

### ISSUE THREAD

**Issue by IrishAdo** [wellington/wellington#190]
As a member of a team every time I build a sass project the comments that it puts in are absolute paths from the route of the server.   like so 

/home/irishado/myprojects/project1/sass/_init.scss

when a colleague builds the project he gets this for the path

/home/colleague/development/myprojects/project1/sass/_init.scss

This causes all the files to be marked as different in git as the comments are changing even though no other changes were applied  can the comments be relative to the sass folder please

then both devs will produce a comment 

/sass/_init.scss

Thanks ADo

**Comment by drewwells** [comment]
I dig it, this sounds annoying. Relative sourcemaps in ruby sass seems straightforward, but libSass seems to be less straightforward. I'm digging through the docs to see how libSass can emit relative sourcemaps.

**Comment by drewwells** [comment]
After some finagling, this appears to correctly emit relative file paths in the sourcmap.

```
test/sass/file.css
build/boom/file.css
build/boom/file.css.map
```

`wt compile --source-map --build build/boom test/sass/file.scss`

```
% cat build/boom/file.css.map
{
	"version": 3,
	"sourceRoot": ".",
	"file": "file.css.map",
	"sources": [
		"../../test/sass/file.scss",
		"../../hdr0"
	],
	"mappings": "AAAA,AAAA,GAAG,CAAC;EACF,KAAK,EAAE,KAAM,GACd",
	"names": []
}                                                                                                                                    

% cat build/boom/file.css
div {
  color: black; }

/*# sourceMappingURL=file.css.map */
```

**Comment by drewwells** [comment]
The resulting sourcemaps look good in Chrome 53

**Comment by drewwells** [comment]
You can test this out by pulling master `go get -u github.com/wellington/wellington/wt`. If you're on OS X and unfamiliar with Go, `brew install --HEAD wellington` will pull the latest changes.

**Comment by IrishAdo** [comment]
Just trying to get the project out at the minute so will test in a couple of days.  I've realised that I didn't give any build information  here is the content of the Gruntfile.js we are using ;-) just happy I figured out how to get it to add the comments to the config file.

```
module.exports = function(grunt) {
  // Config.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    watch: {
      scripts: {
        files: ['./js/src/*.js', '!./js/script.gen.js'],
         tasks: ['jshint', 'concat:tp_boilerplate']
        //  tasks: [ 'concat:tp_boilerplate']
      },
      sass: {
          files: [ 'sass/**/*.scss' ],
          tasks: [ 'wellington:dist' ]
      }
    },
    concat: {
      tp_boilerplate: {
        src: './js/src/**/*.js',
        dest: './js/script.gen.js'
      }
    },
    jshint: {
      options: {
        jshintrc: '.jshintrc',
        reporterOutput: ""
      },
      all: ['js/src/*.js', '!js/script.gen.js']
    },
    wellington: {
        dist: {
            src: [
                'sass/**/*.scss',   // Build all .scss files
                '!sass/**/_*.scss'  // Don't build files starting with "_" into css files
            ],
            options: {
              comment:true,
              style: 'expanded',      // The style of output to be used.
              p: 'sass',       // The base folder that contains the sass.
              b: '.',  // The output folder for the built css.
              d: 'images',    // The input image folder
              gen: 'build/im'  // The output folder for the generated sprite files.
            }
        },
        options: {
            style: 'nested'      // The style of output to be used.
        }
    },

  });

  // Load the tasks...
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-wellington');
  // Default task.
  grunt.registerTask('default', 'watch');

}
```

**Comment by drewwells** [comment]
Looks good, let me know if you run into any issues!
