### ISSUE TITLE
Add function `sprite-names` from compass

### ISSUE THREAD

**Issue by boidolr** [wellington/wellington#192]
To enable access to the image names used to build a sprite the same function as added originally to Compass in https://github.com/Compass/compass/issues/620 (documentation is [here](http://compass-style.org/reference/compass/helpers/sprites/#sprite-names)).
Basically this would allow to loop over the image names in custom code. It's the one thing currently missing which would make wellington a drop in replacement for us.

**Comment by drewwells** [comment]
@boidolr thanks for filing this issue. Can you provide a sample piece of Sass code that uses sprite-names.

**Comment by boidolr** [comment]
Oh wow that was fast. Thanks!

For functions using this see for example https://github.com/Gaya/Retina-Sprites-for-Compass/issues/6 which shows how to use two different resolutions for all used images, switching between the two with media queries.
