### ISSUE TITLE
How to get the STDOUT while watching the file changes?

### ISSUE THREAD

**Issue by YamiOdymel** [wellington/wellington#212]
I'm trying to make a cli program which it will execute the `wt watch` command and stream the `wt watch` output message in realtime. 

The code is very simple and it looks like this: 

```go
command := exec.Command("wt", "watch", "../tocas.sass", "-b", "../../dist/", "-s", "compressed")
command.Stdout = os.Stdout
command.Stderr = os.Stdout
command.Start()
command.Wait()
```

But it only outputs a simple message and the program exited after received an `EOF` signal.

```bash
yamiodymel@OMEN:/mnt/c/Users/Yami Odymel/go/src/github.com/TeaMeow/TocasUI/src/CLI$ go build && ./CLI
File watcher started use `ctrl+d` to exit

yamiodymel@OMEN:/mnt/c/Users/Yami Odymel/go/src/github.com/TeaMeow/TocasUI/src/CLI$
```

Any way to keep outputing the `wt watch` message instead of just exited from the very beginning?

**Comment by drewwells** [comment]
why not call into the public APIs directly instead of calling it like an external program? Take a look at how the cmd package sets up that watch call, you can connect to the code more directly.

You are likely getting an error, set command.Stderr to os.Stderr to see what the error is.

**Comment by YamiOdymel** [comment]
I don't see any STDERR messages. Some programs don't output the error message to the STDERR properly, perhaps `wellington` is the same.

I ended up with [radovskyb/watcher](https://github.com/radovskyb/watcher) file watcher package, which watching the file changes and execute the `wt` command to compile file so I can get the proper message.
