### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by dawidd6** [wellington/wellington#218]
Hello, `wellington` is no longer buildable in Homebrew with latest `v1.0.4` release. 

```
==> go build -ldflags -X github.com/wellington/wellington/version.Version=1.0.4 -o /usr/local/Cellar/wellington/1.0.4/bin/wt wt/main.go
# github.com/wellington/wellington/vendor/github.com/fsnotify/fsevents
vendor/github.com/fsnotify/fsevents/fsevents.go:38:31: constant 36893488147419103231 overflows uint64
vendor/github.com/fsnotify/fsevents/fsevents.go:236:37: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCString
vendor/github.com/fsnotify/fsevents/fsevents.go:237:16: cannot use cPaths (type _Ctype_CFArrayRef) as type _Ctype_CFMutableArrayRef in assignment
vendor/github.com/fsnotify/fsevents/fsevents.go:240:33: constant 36893488147419103231 overflows _Ctype_ulonglong
```

I believe latest commits made to master branch fix those issues.

**Comment by chenrui333** [comment]
@ydnar do you mind creating a new release some time in the future to help out the wellington brew build? Thanks!

**Comment by ydnar** [comment]
@chenrui333 I don’t have commit rights to @wellington/wellington but can probably submit another PR.

**Comment by drewwells** [comment]
What version of Go is home-brew on now?

**Comment by ydnar** [comment]
1.15.1

**Comment by drewwells** [comment]
v1.0.5 released, pr to homebrew opened https://github.com/Homebrew/homebrew-core/pull/60776

**Comment by chenrui333** [comment]
Thanks @drewwells!

**Comment by drewwells** [comment]
Merged upstream. I didn't have issues building it from source in homebrew but there's still work to do in Go libsass to support go modules.
