### ISSUE TITLE
Flag --proj has been deprecated

### ISSUE THREAD

**Issue by tcurdt** [wellington/wellington#220]
I've always used wellington as

	wt watch \
		-p . \
		-b $(TARGET) \
		*.scss

and now I am seeing that `-p` it is deprecated

    Flag --proj has been deprecated, recursive paths can be passed as argument ie. wt compile sass

Deprecated in favor of what? The usage help does not give any further information. That would be nice to add.

I guess in my very case I can probably just remove `-p .`?

**Comment by drewwells** [comment]
Correct, the project idea was dropped. If a folder is passed, it will be recursively scanned for sass files.

**Comment by tcurdt** [comment]
Ah, so the new way would be this instead:

```
wt watch -b $(TARGET) .
```
