### ISSUE TITLE
Codekit Support

### ISSUE THREAD

**Issue by Timoti** [wellington/wellington#30]
This seem exactly what I'm looking for after moving from compass to bourbon last year.  But I'm trying to figure out how I can fit it into my codekit based workflow.  

Is that even possible?  If so could you document that?

**Comment by drewwells** [comment]
I'm not familiar with Codekit. After looking at the website, it appears they need to support it in some way. I'd ping the developer on https://twitter.com/bdkjones

**Comment by Timoti** [comment]
Thanks drew -.  Codekit is great, (libsass supporting)  if opinionated - as is the developer, whose opinion as of today in this respect is that sprites are old hat. :(.

Codekit is great for designers who don't want to get buried in commandline stuff.  Even as a commandline comfy drupal FEdev/designer, I way prefer it to my experience of managing compiling. All my dependency issues disappeared as soon as I ditched ruby, compass, and moved to libsass on codekit running just bourbon/neat.

I did refer Bryan to http://shoptalkshow.com/episodes/148-nathaniel-deal - from which I found out about wellington.  

But in any case I'll delve deeper to see if there's someway to integrate in CK either as a framework or some triggered scripting. Because I think what you've done is really cool.

PS is there a New Zealand connection?

**Comment by drewwells** [comment]
Haha nope, Wellington is a nickname one of the other devs on the project
has for me. I appreciate you looking into CodeKit. I've tried hard to make
integration with other tools very simple. However, it's hard to support
every app out there.

I had been bitten by Ruby dependency problems for many years. One day I
simply couldn't believe that there are no other tools doing this. So I
decided to write one in Go. It was way more work than I thought it would
be, but I'm happy to now have something others can use! Thanks for checking
it out, let me know if there's any ways I can help.

**Comment by drewwells** [comment]
The yet unreleased 1.0 release will be cli compatible with Compass. So you can get Codekit support by renaming the binary (or symlinking) ie. `ln -s compass wt`

**Comment by Timoti** [comment]
thanks  - does that mean compass is required ? Compass already has spriting but doesn't do libsass - i'm looking for a libsass friendly way to sprite with codekit - did you mean that is possible? Or praps I need to harden up and get back on the command line for this side of the (vege)sausage?

**Comment by drewwells** [comment]
CodeKit is a black box since it's closed source. However, we now support
compass style cli calls. So `compass compile --args` is compatible with `wt
compile --args`. Assuming codekit uses the cli to process sass files, you
should be able to symlink compass to wt and use codekit as is. This is
going to be added in wt 1.0, which you can try out by installing HEAD from
brew. brew install --HEAD wellington
