### ISSUE TITLE
How do I set a CSS folder path?

### ISSUE THREAD

**Issue by fronteed** [wellington/wellington#36]
In compass, there's `config.rb` file, which supports `css_dir` option:

```
css_dir = 'assets/css'
```

When I use something like `$icons: sprite-map("icons/*.png", $spacing: 5px)`, compass already knows that the real path is `assets/css/icons/`.

How do I make this using Wellington?
I usually store my sass files in the `assets/sass` folder. So I also use `sass_dir` option.

**Comment by drewwells** [comment]
Use `--images-dir` to specify the image directory for sprites (compatible with Compass).

`css-dir` is the build location for generated css. Compass may also look for css files there, but you can intermingle those in your sass directory just fine.  I'm not aware of any way that compass looks for images relative to `css_dir`. 

For instance, with the file `{project}/sass/file.scss`

    $icons: sprite-map("icons/*.png")

Then running
```
${project}: compass compile --css-dir css --sass-dir sass
No files were found in the load path matching "icons/*.png". Your current load paths 
are: {project}/images
```

Are you specifying other options that may enable this behavior?

**Comment by drewwells** [comment]
Assume this is working now, reopen if you still have issues.
