### ISSUE TITLE
Grunt and Gulp

### ISSUE THREAD

**Issue by fronteed** [wellington/wellington#42]
How do I use Wellington through Grunt and Gulp?

**Comment by drewwells** [comment]
I've been puttering around with a Grunt wrapper, I'll admit this is out of my expertise. I'll push that up whenever it's working reliably. I could use help with a Gulp wrapper.

**Comment by drewwells** [comment]
Super alpha, but give this a try: https://www.npmjs.com/package/grunt-wellington

**Comment by calibre** [comment]
Any chance of a gulp wrapper for this? Would love to get Wellington into a gulp build pipeline. The Compass image helpers are the last thing we can't decouple from our current build :(

**Comment by drewwells** [comment]
@andystalick Are you using a grunt or gulp wrapper for wellington?

**Comment by astalick** [comment]
I am using grunt-wellington

**Comment by drewwells** [comment]
I don't have any plans to support a gulp plugin, but would gladly link to one it appeared!  #82 is designed to totally emulate compass. After that is done, you could in theory symlink compass to wt and any existing compass gulp wrappers would work.

**Comment by drewwells** [comment]
#102 fixes this

**Comment by drewwells** [comment]
This needs testing. The latest master `brew install --HEAD wellington` supports most compass cli arguments. So by symlinking 

```
ln -s $(which wt) /usr/local/bin/compass
```

It will be possible to use wt cli as a drop in replacement for wt cli

**Comment by drewwells** [comment]
grunt-wellington will need backwards incompatible changes for 1.0 see wellington/grunt-wellington#1
