### ISSUE TITLE
Use Node instead of Go

### ISSUE THREAD

**Issue by fronteed** [wellington/wellington#54]
Overall installation process looks a bit tricky because of the Go dependence.

Why don't you use node.js (or io.js) instead of Go lang? 

Node would make Wellington much more portable, especially for the apps like (prepros.io)[Prepros] and (https://incident57.com/codekit/)[Codekit].

**Comment by drewwells** [comment]
What part of installation are you having trouble with? Codekit is an OS X only app and you can install Wellington with brew which manages the installation for you and has no runtime dependencies.

**Comment by fronteed** [comment]
Wellington should not force me to install any third-party libraries outside the Prepros or Codekit. In other way, it won't be wide-used.

**Comment by drewwells** [comment]
Wellington installed via Brew has no dependencies. Did you have an issue
installing with Brew?

**Comment by fronteed** [comment]
I've brew on OS X, but not on Windows.

**Comment by drewwells** [comment]
Created https://github.com/wellington/wellington/issues/55 to address windows support. I've never tried compiling libsass on Windows, but never hurts to try ;)

**Comment by drewwells** [comment]
There's no plans to switch to Node.

**Comment by fronteed** [comment]
Nice tool was killed using Go dependence.
