### ISSUE TITLE
Using in Middleman workflow

### ISSUE THREAD

**Issue by dmitriy-korotayev** [wellington/wellington#61]
Greetings.

I use Middleman with Sass and Compass for my frontend development workflow and got very interested in your project because of performance and svg sprite generation. 
Still, it's unclear to me how could I use Wellington in Middleman as easy as Compass.
Can you help on this part? 

You can check out compass middleman integration here: https://github.com/middleman/middleman-compass

If I could use it with all the tools I got most of performance with, it could be a lifesaver!
Thanks

**Comment by drewwells** [comment]
Middleman uses compass directly as a lib, so it will be a bit trickier to use Wellington. Does middleman have a libsass middleware?

**Comment by dmitriy-korotayev** [comment]
I don't actually know. I just got to dropping sass generation through Middleman and will just build my sass through grunt
