### ISSUE TITLE
Push 0.7.0 to Homebrew

### ISSUE THREAD

**Issue by astalick** [wellington/wellington#67]
Please push the latest version into Homebrew for those of us too lazy to build it ourselves.

Also, BTW, 0.6.0 reports version 0.4.0 with the -version flag.

Thanks!

**Comment by drewwells** [comment]
I'll push up 0.7.0. You might also want to try out master. It's using the new 3.2.0 beta releases of libsass with a lot of enhancements. https://github.com/sass/libsass/issues?q=milestone%3A3.2+is%3Aclosed Fair warning, the file watcher is not working on master.

    brew uninstall wellington && brew install --HEAD wellington

**Comment by drewwells** [comment]
```
brew info wellington
wellington: stable 0.7.0 (bottled), HEAD
https://github.com/wellington/wellington
/usr/local/Cellar/wellington/0.7.0 (4 files, 7.0M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/wellington.rb
==> Dependencies
Build: go ✔, pkg-config ✔, autoconf ✔, automake ✔, libtool ✔
```

```
/usr/local/bin/wt -v
v0.7.0
```

wt reports correct version now as well
