### ISSUE TITLE
Is output style unsupported?

### ISSUE THREAD

**Issue by sashka** [wellington/wellington#96]
It looks like ``wt -c=false -s=nested simple.scss`` produces the same output as ``wt -c=false -s=compressed simple.scss``

wt version:
```
Wellington: v0.8.1
   libsass: 3.2.4
```

**Comment by drewwells** [comment]
Thanks for the bug report! wt honors output style now... libsass 3.2.5 has an interesting way of combining source comments and compressed output style

```
wt -s compressed main.scss
/* line 1, main.scss */div p{color:red}
```

**Comment by sashka** [comment]
Thanks!
